name: Build furnace (Android)

on:
  push:
    branches: android-actions-test
  pull_request:
    branches: android-actions-test

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - name: Set package identifier
      id: package-identify
      run: |
        package_name="furnace-${GITHUB_SHA}"
        package_ext=""
        
        package_name="${package_name}-Android"
        package_ext=".apk"

        echo "Package identifier: ${package_name}"
        echo "Package file: ${package_name}${package_ext}"

        echo "id=${package_name}" >> $GITHUB_OUTPUT
        echo "filename=${package_name}${package_ext}" >> $GITHUB_OUTPUT


    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install \
          libsdl2-dev \
          libfmt-dev \
          librtmidi-dev \
          libsndfile1-dev \
          zlib1g-dev \
          libjack-jackd2-dev

    - name: Build (run Gradle)
      run: |
        cd ${PWD}/android/
        ./gradlew assembleDebug
        ./gradlew --stop
        cd ../..

    - name: Package
      run: |

        mkdir -p target/furnace
        # make -C ${PWD}/build DESTDIR=${PWD}/target/furnace install
        mv ${PWD}/android/app/build/outputs/apk/debug/app-debug.apk target/furnace/${steps.package-identify.outputs.id}.apk
        pushd target/furnace

        # cp -v ../../res/logo.png .DirIcon

        # cd usr

        # mv bin/furnace ..
        # rmdir bin

        # rm -r share/applications
        # rm -r share/doc
        # rm -r share/icons
        # rm -r share/licenses
        # rm -r share/metainfo

        # rmdir share

        # cd ..

        # cp ../../LICENSE .
        # cp ../../res/releaseReadme/unstable-other.txt .
        # cp -r ../../papers papers
        # rmdir usr

        popd

        cd target

        # tar -zcv -f ../${{ steps.package-identify.outputs.filename }} furnace

    - name: Upload artifact
      if: ${{ github.repository == 'Eknous-P/furnace' && github.ref_name == 'android-actions-test' }}
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ steps.package-identify.outputs.id }}
        path: ${{ steps.package-identify.outputs.filename }}



